image: docker:stable

stages:
  - Build e Push image
  - Documentation

variables:
    ALPINE_RELEASE: "3.13"
    ALPINE_VERSION: "3.13.2"
    ALPINE_VERSION_DATE: "Feb, 17 2021"
    MARIADB_VERSION: "10.5.8-r0"

update readme:
    stage: Documentation
    variables:
        DOCKERHUB_USERNAME: "$DOCKER_HUB_USER"
        DOCKERHUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
        DOCKERHUB_REPO_PREFIX: "maurosoft1973"
        DOCKERHUB_REPO_NAME: "alpine-mariadb"
        DOCKERHUB_SHORT_DESCRIPTION: "MariaDB Docker image running on Alpine Linux"
    only:
        - master
    script:
        - LATEST_UPDATE=$(date +"%d.%m.%Y %H:%M:%S")
        - echo "Generate README for Version ${MARIADB_VERSION}"
        - sed "s/\%ALPINE_VERSION\%/${ALPINE_VERSION}/g" README.tpl > README.md1
        - sed "s/\%ALPINE_VERSION_DATE\%/${ALPINE_VERSION_DATE}/g" README.md1 > README.md2
        - sed "s/\%MARIADB_VERSION\%/${MARIADB_VERSION}/g" README.md2 > README.md3
        - sed "s/\%LATEST_UPDATE\%/${LATEST_UPDATE}/g" README.md3 > README.md
        - FULL_DESCRIPTION=$(if [ -f "$(pwd)/README.md" ]; then cat "$(pwd)/README.md"; else echo ""; fi)
        - docker pull maurosoft1973/alpine-readme-to-dockerhub:latest
        - docker run --rm -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX" -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME" -e SHORT_DESCRIPTION="$DOCKERHUB_SHORT_DESCRIPTION" -e FULL_DESCRIPTION="$FULL_DESCRIPTION" maurosoft1973/alpine-readme-to-dockerhub

amd64 test build:
    image: docker
    stage: Build e Push image
    only:
        - master
    variables:
        RELEASE: "TEST"
    script:
        - apk add bash
        - bash ./build-image.sh -ar=$ALPINE_RELEASE -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -r=$RELEASE

amd64 current build:
    stage: Build e Push image
    variables:
        RELEASE: "CURRENT"
    only:
        - master
    script:
        - apk add bash
        - bash ./build-image.sh -ar=$ALPINE_RELEASE -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -r=$RELEASE

amd64 latest build:
    stage: Build e Push image
    variables:
        RELEASE: "LATEST"
    only:
        - master
    script:
        - apk add bash
        - bash ./build-image.sh -ar=$ALPINE_RELEASE -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -r=$RELEASE

